In [3]:
import numpy as np
np.finfo(np.float64).eps

2.220446049250313e-16

In [6]:
a1=np.array([[1,1000],[0,1]])
a2=np.array([[1,1000],[0.001,1]])
print(a1)
print(a2)

[[   1 1000]
 [   0    1]]
[[1.e+00 1.e+03]
 [1.e-03 1.e+00]]


In [7]:
covariance=np.cov(a1)
np.linalg.eig(covariance)

(array([4.99001000e+05, 4.33680869e-18]),
 array([[ 0.9999995, -0.001001 ],
        [ 0.001001 ,  0.9999995]]))